export type BusinessType = 
  | 'retail'
  | 'dining'
  | 'wellness'
  | 'hospitality'
  | 'service'
  | 'entertainment'
  | 'property'
  | 'automotive'
  | 'education'
  | 'other';

export interface BusinessInfo {
  name: string;
  type: string;
  description: string;
  targetAudience: string;
  uniqueValueProposition: string;
  competitors: string;
  budget: string;
  timeline: string;
  goals: string;
  challenges: string;
  visualIdentity: string;
  brandVoice: string;
  brandValues: string;
  brandPersonality: string;
  brandStory: string;
  brandPromise: string;
  brandPositioning: string;
  brandMission: string;
  brandVision: string;
  brandTagline: string;
  brandColors: string;
  brandFonts: string;
  brandLogo: string;
  brandImages: string;
  brandVideos: string;
  brandAudio: string;
  brandSocialMedia: string;
  brandWebsite: string;
  brandEmail: string;
  brandPhone: string;
  brandAddress: string;
  brandHours: string;
  brandLocation: string;
  brandReviews: string;
  brandTestimonials: string;
  brandCaseStudies: string;
  brandAwards: string;
  brandCertifications: string;
  brandPartners: string;
  brandSponsors: string;
  brandEvents: string;
  brandNews: string;
  brandPress: string;
  brandBlog: string;
  brandPodcast: string;
  brandYouTube: string;
  brandTikTok: string;
  brandInstagram: string;
  brandFacebook: string;
  brandTwitter: string;
  brandLinkedIn: string;
  brandPinterest: string;
  brandSnapchat: string;
  brandReddit: string;
  brandQuora: string;
  brandMedium: string;
  brandTumblr: string;
  brandFlickr: string;
  brandVimeo: string;
  brandDribbble: string;
  brandBehance: string;
  brandGitHub: string;
  brandStackOverflow: string;
  brandProductHunt: string;
  brandAngelList: string;
  brandCrunchbase: string;
  brandPitchbook: string;
  brandLinkedInCompany: string;
  brandGlassdoor: string;
  brandIndeed: string;
  brandMonster: string;
  brandCareerBuilder: string;
  brandZipRecruiter: string;
  brandDice: string;
  brandHired: string;
  brandAngelListJobs: string;
  brandStackOverflowJobs: string;
  brandGitHubJobs: string;
  brandLinkedInJobs: string;
  brandIndeedJobs: string;
  brandGlassdoorJobs: string;
  brandMonsterJobs: string;
  brandCareerBuilderJobs: string;
  brandZipRecruiterJobs: string;
  brandDiceJobs: string;
  brandHiredJobs: string;
  brandAngelListCompanies: string;
  brandCrunchbaseCompanies: string;
  brandLinkedInCompanies: string;
  brandGlassdoorCompanies: string;
  brandIndeedCompanies: string;
  brandMonsterCompanies: string;
  brandCareerBuilderCompanies: string;
  brandZipRecruiterCompanies: string;
  brandDiceCompanies: string;
  brandHiredCompanies: string;
  brandAngelListInvestors: string;
  brandCrunchbaseInvestors: string;
  brandLinkedInInvestors: string;
  brandGlassdoorInvestors: string;
  brandIndeedInvestors: string;
  brandMonsterInvestors: string;
  brandCareerBuilderInvestors: string;
  brandZipRecruiterInvestors: string;
  brandDiceInvestors: string;
  brandHiredInvestors: string;
  brandAngelListStartups: string;
  brandCrunchbaseStartups: string;
  brandLinkedInStartups: string;
  brandGlassdoorStartups: string;
  brandIndeedStartups: string;
  brandMonsterStartups: string;
  brandCareerBuilderStartups: string;
  brandZipRecruiterStartups: string;
  brandDiceStartups: string;
  brandHiredStartups: string;
  brandAngelListPeople: string;
  brandCrunchbasePeople: string;
  brandLinkedInPeople: string;
  brandGlassdoorPeople: string;
  brandIndeedPeople: string;
  brandMonsterPeople: string;
  brandCareerBuilderPeople: string;
  brandZipRecruiterPeople: string;
  brandDicePeople: string;
  brandHiredPeople: string;
}

export interface RoadmapSection {
  title: string;
  description: string;
  shortTermActions: string[];
  longTermGoals: string[];
  kpis: string[];
}

export interface MarketingTip {
  id: string;
  title: string;
  description: string;
  category: string;
  example?: string;
}

export interface MarketingPlan {
  businessInfo: BusinessInfo;
  summary: string;
  roadmap: RoadmapSection[];
  tips: string[];
}